<?php
return ['title' => 'Ejemplo de localización', 'Save' => 'حفظ', 'Back' => 'عودة', 'Cancel' => 'إلغاء', 'New Record' => 'رقم قياسي جديد', 'Trash' => 'قمامة، يدمر، يهدم', 'Back' => 'عودة', 'Export' => 'تصدير','Starting Number'=>'رقم البداية ','Applicable To'=>'تنطبق على ','Applicable From'=>'ينطبق من ','Number Suffix'=>'رقم لاحقة ','Number Prefix'=>'بادئة 
الرقم ','Invoice Number Format'=>'تنسيق رقم الفاتورة ','New Settings'=>'إعدادات جديدة ','Settings Lists'=>'قوائم الإعدادات ','PDF'=>'بي دي إف ','Copy'=>'نسخ ','Print'=>'طباعة ','Choose an option'=>'إختر خيار ','S.No'=>'لاs ','Action'=>'عمل ','Branch settings'=>'إعدادات الفرع',
'Header'=>'رأس','Footer'=>'تذييل','Tax Group'=>'المجموعة الضريبية','Tax'=>'ضريبة','Tax Settings'=>'إعدادات الضرائب','Tax List'=>'قائمة الضرائب','New Tax'=>'ضريبة جديدة','Tax Trash List'=>'قائمة المهملات الضريبية','Tax List View'=>'عرض قائمة الضرائب','New Tax Groups'=>'مجموعات ضريبية جديدة','Tax Group Trash List'=>'قائمة مهملات المجموعة الضريبية','Tax Group List View'=>'عرض قائمة المجموعة الضريبية','Customer Group Trash list'=>'قائمة مهملات مجموعة العملاء','Customer Category Trash list'=>'قائمة مهملات فئة العملاء','Customer Type Trash List'=>'قائمة مهملات نوع العميل','Suppliergroup Information details form'=>'نموذج تفاصيل معلومات مجموعة الموردين','Supplier Type Trash List'=>'قائمة المهملات نوع المورد','Supplier Type details form'=>'نموذج تفاصيل نوع المورد','Vendor CategoryTrash Details List'=>'قائمة تفاصيل سلة مهملات فئة البائع','Vendor Type Trash List'=>'قائمة مهملات نوع البائع','Payment Details Form'=>'نموذج تفاصيل الدفع','Payment Terms Trash List'=>'قائمة المهملات شروط الدفع','Trash Department List'=>'قائمة قسم المهملات','Terms and Conditions Trash List'=>'الشروط والأحكام قائمة المهملات','Currency List'=>'قائمة العملات','New Currency'=>'عملة ','Currency Trash List'=>'قائمة سلة مهملات العملات','VendorTypeTrashList'=>'قائمة مهملات نوع البائع','Department Trash'=>'قسم المهملات','Tax Group'=>'المجموعة الضريبية','Tax Group Name'=>'اسم المجموعة الضريبية','Tax Percentage'=>'نسبة الضريبة','Note'=>'ملحوظة','Vendor Category Trash'=>'سلة مهملات فئة البائع',
// Email Settings (21-07-2022)
'EmailSettings'=>'إعدادات البريد الإلكتروني',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',''=>'',


];

